// Agent Relay for OpenCode.
// npm package @agent-relay/opencode-plugin, loaded from opencode.json's
// "plugin" list. Generated by scripts/build.mjs from the Agent Relay desktop's
// plugin (protocol version 2, template 6319cfb); do not edit.
//
// When the desktop's own copy is installed in OpenCode's plugins directory
// (it carries AGENT_RELAY_OPENCODE_PLUGIN=), or the person turned the
// desktop's OpenCode setting off (agent-relay.js.off), this package does
// nothing, so the plugin never runs twice in one process.
//
// Lets Agent Relay deliver a relay message into a session open in this
// OpenCode process and read the answer back, with no TCP port and no
// keystrokes. Each process listens on its own Unix socket,
// <runtime>/<pid>.sock, in a directory only this user can enter, and
// records the sessions it holds in <runtime>/<pid>.json. The socket answers
// only these requests, and only for a session this process holds:
//
//   GET  /session/status
//   GET  /session/<id>
//   GET  /session/<id>/message
//   GET  /session/<id>/message/<message id>
//   POST /session/<id>/prompt_async   (one text part, a msg_relay_ id)
//
// Everything else is 404. Nothing is forwarded verbatim: each request is
// rebuilt for OpenCode's in-process server.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const RUNTIME = path.join(os.homedir(), ".agentworkforce", "desktop", "opencode");
const VERSION = 2;
const SESSION = /^ses_[A-Za-z0-9]{4,128}$/;
const MESSAGE = /^msg_[A-Za-z0-9_]{4,128}$/;
const RELAY_MESSAGE = /^msg_relay_[0-9a-f]{32}$/;
const MAX_TEXT = 65536;
const MAX_REQUEST = 262144;

function json(status, value) {
  return new Response(value === undefined ? null : JSON.stringify(value), {
    status,
    headers: { "content-type": "application/json" },
  });
}

function privateRuntime() {
  const uid = process.getuid?.();
  if (uid === undefined) return false;
  try {
    fs.mkdirSync(RUNTIME, { recursive: true, mode: 0o700 });
    const stat = fs.lstatSync(RUNTIME);
    return stat.isDirectory() && stat.uid === uid && (stat.mode & 0o077) === 0;
  } catch {
    return false;
  }
}

function alive(pid) {
  try {
    process.kill(pid, 0);
    return true;
  } catch (error) {
    return error?.code === "EPERM";
  }
}

// The session this process was started on, from its own command line: the
// TUI runs plugins in a worker whose argv is not the user's, and opening a
// session publishes no event. `--session <id>` (or `-s`) names one;
// `--continue` (or `-c`) resumes the latest in the directory.
function startedOn() {
  try {
    const result = Bun.spawnSync(["ps", "-o", "args=", "-p", String(process.pid)]);
    const words = result.stdout.toString().trim().split(/\s+/);
    // `--fork` is a boolean flag: `--fork` and `--fork=true` fork; `--fork=false` does not.
    if (words.some((word) => word === "--fork" || (word.startsWith("--fork=") && !/^--fork=(false|0|no)$/i.test(word)))) {
      return {};
    }
    for (let index = 1; index < words.length; index++) {
      const word = words[index];
      if (word === "--session" || word === "-s") return { session: words[index + 1] };
      if (word.startsWith("--session=")) return { session: word.slice("--session=".length) };
      if (word === "--fork") return {};
    }
    return { latest: words.includes("--continue") || words.includes("-c") };
  } catch {
    return {};
  }
}

// Records and sockets left by OpenCode processes that died without cleaning
// up. The probe never trusts them anyway: it checks the pid, its start time
// and who answers on the socket.
function sweep() {
  for (const name of fs.readdirSync(RUNTIME)) {
    const match = /^(\d+)\.(sock|json)$/.exec(name);
    if (match && Number(match[1]) !== process.pid && !alive(Number(match[1]))) {
      try {
        fs.unlinkSync(path.join(RUNTIME, name));
      } catch {}
    }
  }
}

// Every shell OpenCode runs for a session (the bash tool, a typed command)
// carries that session's id, so the desktop can tell which session a reply
// over its relay-send socket comes from, as Grok's GROK_SESSION_ID does. The
// desktop believes it only for a session this process holds in its record,
// found by walking up to this process, so the tag is set even when this
// process could not open its socket: alone it names nobody.
async function tag(input, output) {
  const id = input?.sessionID;
  if (typeof id !== "string" || !SESSION.test(id) || !output) return;
  // Added to the object OpenCode passes in, which it then reads back.
  if (!output.env || typeof output.env !== "object") output.env = {};
  output.env.AGENT_RELAY_OPENCODE_SESSION = id;
}

// OpenCode's global config directory, as OpenCode and the desktop resolve it.
function configDirectory() {
  const xdg = process.env.XDG_CONFIG_HOME?.trim();
  return path.join(xdg && xdg.startsWith("/") ? xdg : path.join(os.homedir(), ".config"), "opencode");
}

// The desktop's copy of this plugin serves the process, or the person turned
// the desktop's OpenCode setting off. Either way this package stays out.
function deferToDesktop() {
  const file = path.join(configDirectory(), "plugins", "agent-relay.js");
  if (fs.existsSync(`${file}.off`)) return true;
  try {
    const head = fs.readFileSync(file, "utf8").split("\n").slice(0, 5);
    return head.some((line) => line.includes("AGENT_RELAY_OPENCODE_PLUGIN="));
  } catch {
    return false;
  }
}

const CLAIM = Symbol.for("agent-relay.opencode-plugin");

export const AgentRelay = async ({ client, directory }) => {
  // A server the relay launched itself has its own authenticated route.
  if (process.env.AGENT_RELAY_MANAGED_SESSION_MARKER) return {};
  if (deferToDesktop()) return {};
  // Two versions of this package (global and project opencode.json) load
  // separately; only the first serves the process.
  if (globalThis[CLAIM]) return {};
  const claim = { version: VERSION };
  globalThis[CLAIM] = claim;
  const tagging = { "shell.env": tag };
  if (typeof Bun === "undefined" || !client?._client?.getConfig) return tagging;
  if (!privateRuntime()) return tagging;
  try {
    sweep();
  } catch {}

  const config = client._client.getConfig();
  const socket = path.join(RUNTIME, `${process.pid}.sock`);
  const record = path.join(RUNTIME, `${process.pid}.json`);
  // Sessions this process holds: top-level sessions it created or ran a
  // turn in. Subagent sessions (with a parent) are never listed.
  const sessions = new Map();
  const children = new Set();

  async function opencode(method, pathname, body) {
    const headers = new Headers(config.headers ?? {});
    headers.set("accept", "application/json");
    if (body !== undefined) headers.set("content-type", "application/json");
    const request = new Request(new URL(pathname, config.baseUrl), {
      method,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    return (config.fetch ?? fetch)(request);
  }

  // OpenCode's answer, passed on. A null-body status (204 for an accepted
  // prompt_async, 205, 304) must carry no body, or Response throws.
  async function relay(response) {
    const empty = [101, 204, 205, 304].includes(response.status);
    return new Response(empty ? null : await response.arrayBuffer(), {
      status: response.status,
      headers: empty
        ? {}
        : { "content-type": response.headers.get("content-type") ?? "application/json" },
    });
  }

  let writing = Promise.resolve();
  let stopped = false;
  function save() {
    writing = writing
      .then(() => {
        if (stopped) return;
        // Every session this process holds: one left out could not be
        // delivered to while the process still holds it.
        const list = [...sessions.values()].sort((a, b) => b.updated - a.updated);
        const temporary = `${record}.${Math.random().toString(16).slice(2)}.tmp`;
        fs.writeFileSync(
          temporary,
          JSON.stringify({
            version: VERSION,
            pid: process.pid,
            socket,
            directory,
            sessions: list,
          }),
          { mode: 0o600 },
        );
        fs.renameSync(temporary, record);
      })
      .catch(() => {});
    return writing;
  }

  function remember(info) {
    if (!info || typeof info.id !== "string" || !SESSION.test(info.id)) return;
    if (info.parentID) {
      children.add(info.id);
      sessions.delete(info.id);
      return;
    }
    sessions.set(info.id, {
      id: info.id,
      title: typeof info.title === "string" ? info.title.slice(0, 200) : "",
      directory: typeof info.directory === "string" ? info.directory : directory,
      updated: Number(info.time?.updated ?? Date.now()),
    });
    save();
  }

  async function touch(id) {
    if (typeof id !== "string" || !SESSION.test(id) || children.has(id)) return;
    const known = sessions.get(id);
    if (known) {
      known.updated = Date.now();
      save();
      return;
    }
    try {
      const response = await opencode("GET", `/session/${id}`);
      if (response.ok) remember(await response.json());
    } catch {}
  }

  async function handle(request) {
    const url = new URL(request.url);
    const parts = url.pathname.split("/").filter(Boolean);
    if (url.search) return json(404);
    if (request.method === "GET" && parts.length === 2 && parts[0] === "session" && parts[1] === "status") {
      const response = await opencode("GET", "/session/status");
      if (!response.ok) return relay(response);
      const all = await response.json();
      const mine = {};
      for (const id of sessions.keys()) if (all?.[id]) mine[id] = all[id];
      return json(200, mine);
    }
    if (parts[0] !== "session" || !sessions.has(parts[1] ?? "")) return json(404);
    const id = parts[1];
    if (request.method === "GET" && parts.length === 2) {
      return relay(await opencode("GET", `/session/${id}`));
    }
    if (request.method === "GET" && parts.length === 3 && parts[2] === "message") {
      return relay(await opencode("GET", `/session/${id}/message`));
    }
    if (request.method === "GET" && parts.length === 4 && parts[2] === "message" && MESSAGE.test(parts[3])) {
      return relay(await opencode("GET", `/session/${id}/message/${parts[3]}`));
    }
    if (request.method === "POST" && parts.length === 3 && parts[2] === "prompt_async") {
      const text = await request.text();
      if (text.length > MAX_REQUEST) return json(413);
      let body;
      try {
        body = JSON.parse(text);
      } catch {
        return json(400);
      }
      if (body === null || typeof body !== "object" || Array.isArray(body)) return json(400);
      const part = Array.isArray(body?.parts) && body.parts.length === 1 ? body.parts[0] : undefined;
      if (
        Object.keys(body ?? {}).some((key) => key !== "messageID" && key !== "parts") ||
        typeof body.messageID !== "string" ||
        !RELAY_MESSAGE.test(body.messageID) ||
        part?.type !== "text" ||
        typeof part.text !== "string" ||
        part.text.length === 0 ||
        part.text.length > MAX_TEXT
      ) {
        return json(400);
      }
      return relay(
        await opencode("POST", `/session/${id}/prompt_async`, {
          messageID: body.messageID,
          parts: [{ type: "text", text: part.text }],
        }),
      );
    }
    return json(404);
  }

  try {
    fs.unlinkSync(socket);
  } catch {}
  let server;
  try {
    server = Bun.serve({
      unix: socket,
      async fetch(request) {
        try {
          return await handle(request);
        } catch {
          return json(502);
        }
      },
    });
    fs.chmodSync(socket, 0o600);
  } catch {
    return tagging;
  }
  save();

  // Once the server is up (calling it while plugins load would wait on
  // itself), hold the session the TUI was started on.
  const startup = setTimeout(async () => {
    const started = startedOn();
    if (started.session) {
      await touch(started.session);
    } else if (started.latest) {
      try {
        const response = await opencode("GET", "/session");
        const list = response.ok ? await response.json() : [];
        const latest = (Array.isArray(list) ? list : [])
          .filter((info) => !info.parentID && !info.time?.archived && info.directory === directory)
          .sort((a, b) => (b.time?.updated ?? 0) - (a.time?.updated ?? 0))[0];
        if (latest) remember(latest);
      } catch {}
    }
  }, 1000);

  let closed = false;
  const close = () => {
    if (closed) return;
    closed = true;
    try {
      server?.stop(true);
    } catch {}
    for (const file of [socket, record]) {
      try {
        fs.unlinkSync(file);
      } catch {}
    }
  };
  process.once("exit", close);

  // OpenCode calls a plugin's dispose hook when it tears an instance down
  // (before it emits server.instance.disposed): stop the listener, the
  // startup timer and the exit hook, remove the socket and record, and
  // release the process claim, so a reload in the same process serves again.
  const dispose = async () => {
    stopped = true;
    clearTimeout(startup);
    process.removeListener("exit", close);
    close();
    if (globalThis[CLAIM] === claim) delete globalThis[CLAIM];
  };

  return {
    "shell.env": tag,
    dispose,
    event: async ({ event }) => {
      const properties = event?.properties ?? {};
      switch (event?.type) {
        case "session.created":
        case "session.updated":
          if (sessions.has(properties.info?.id) || event.type === "session.created") {
            remember(properties.info);
          }
          break;
        case "session.deleted":
          if (sessions.delete(properties.info?.id)) save();
          break;
        case "message.updated":
          await touch(properties.info?.sessionID);
          break;
        case "server.instance.disposed":
          await dispose();
          break;
      }
    },
  };
};
