#!/usr/bin/env node
// Renders index.js from the Agent Relay desktop's OpenCode plugin template,
// so the npm package speaks exactly the protocol the desktop's probe expects.
//
//   node scripts/build.mjs <relay-desktop checkout> [--check]
//
// The template is probe/src/relay/opencode/agent-relay.js and the version is
// PLUGIN_VERSION in probe/src/relay/opencode.rs. --check fails when the
// committed index.js differs from what the template renders.

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const output = path.join(here, "..", "index.js");
const args = process.argv.slice(2);
const check = args.includes("--check");
const desktopArg = args.find((arg) => !arg.startsWith("--"));
if (!desktopArg) {
  console.error("usage: node scripts/build.mjs <relay-desktop checkout> [--check]");
  process.exit(2);
}
// Absolute, so the git pathspec below resolves from inside the checkout.
const desktop = path.resolve(desktopArg);

const templatePath = path.join(desktop, "probe/src/relay/opencode/agent-relay.js");
const rustPath = path.join(desktop, "probe/src/relay/opencode.rs");
const template = fs.readFileSync(templatePath, "utf8");
const version = /pub const PLUGIN_VERSION: u32 = (\d+);/.exec(fs.readFileSync(rustPath, "utf8"))?.[1];
if (!version) throw new Error("PLUGIN_VERSION not found in opencode.rs");
let commit = "unknown";
try {
  commit = execFileSync("git", ["-C", desktop, "log", "-1", "--format=%h", "--", "probe/src/relay/opencode/agent-relay.js"], {
    encoding: "utf8",
  }).trim() || "unknown";
} catch {}

function replaceOnce(source, from, to) {
  const index = source.indexOf(from);
  if (index < 0 || source.indexOf(from, index + from.length) >= 0) {
    throw new Error(`template changed: expected exactly one ${JSON.stringify(from.slice(0, 60))}`);
  }
  return source.slice(0, index) + to + source.slice(index + from.length);
}

let source = template;
source = replaceOnce(
  source,
  `// Installed and removed by Agent Relay's "OpenCode sessions" setting; edits
// to this file are overwritten. AGENT_RELAY_OPENCODE_PLUGIN=__VERSION__
`,
  `// npm package @agent-relay/opencode-plugin, loaded from opencode.json's
// "plugin" list. Generated by scripts/build.mjs from the Agent Relay desktop's
// plugin (protocol version ${version}, template ${commit}); do not edit.
//
// When the desktop's own copy is installed in OpenCode's plugins directory
// (it carries AGENT_RELAY_OPENCODE_PLUGIN=), or the person turned the
// desktop's OpenCode setting off (agent-relay.js.off), this package does
// nothing, so the plugin never runs twice in one process.
`,
);
source = replaceOnce(source, `import path from "node:path";\n`, `import os from "node:os";\nimport path from "node:path";\n`);
source = replaceOnce(
  source,
  "const RUNTIME = __RUNTIME__;",
  `const RUNTIME = path.join(os.homedir(), ".agentworkforce", "desktop", "opencode");`,
);
source = replaceOnce(source, "const VERSION = __VERSION__;", `const VERSION = ${version};`);
source = replaceOnce(
  source,
  "export const AgentRelay = async ({ client, directory }) => {\n" +
    "  // A server the relay launched itself has its own authenticated route.\n" +
    "  if (process.env.AGENT_RELAY_MANAGED_SESSION_MARKER) return {};\n",
  `// OpenCode's global config directory, as OpenCode and the desktop resolve it.
function configDirectory() {
  const xdg = process.env.XDG_CONFIG_HOME?.trim();
  return path.join(xdg && xdg.startsWith("/") ? xdg : path.join(os.homedir(), ".config"), "opencode");
}

// The desktop's copy of this plugin serves the process, or the person turned
// the desktop's OpenCode setting off. Either way this package stays out.
function deferToDesktop() {
  const file = path.join(configDirectory(), "plugins", "agent-relay.js");
  if (fs.existsSync(\`\${file}.off\`)) return true;
  try {
    const head = fs.readFileSync(file, "utf8").split("\\n").slice(0, 5);
    return head.some((line) => line.includes("AGENT_RELAY_OPENCODE_PLUGIN="));
  } catch {
    return false;
  }
}

const CLAIM = Symbol.for("agent-relay.opencode-plugin");

export const AgentRelay = async ({ client, directory }) => {
  // A server the relay launched itself has its own authenticated route.
  if (process.env.AGENT_RELAY_MANAGED_SESSION_MARKER) return {};
  if (deferToDesktop()) return {};
  // Two versions of this package (global and project opencode.json) load
  // separately; only the first serves the process.
  if (globalThis[CLAIM]) return {};
  globalThis[CLAIM] = VERSION;
`,
);
// Fixes not yet in the desktop template (AgentWorkforce/relay-desktop, same
// fixes proposed there). Each anchor must match exactly once, so the build
// fails loudly when the template changes and the patch can be dropped.
//
// 1. `--session <id> --fork` opens a new fork: never hold the source session.
source = replaceOnce(
  source,
  `    const words = result.stdout.toString().trim().split(/\\s+/);
    for (let index = 1;`,
  `    const words = result.stdout.toString().trim().split(/\\s+/);
    if (words.includes("--fork")) return {};
    for (let index = 1;`,
);
// 2. A prompt body that is valid JSON but not an object (null, an array, a
//    number) is the caller's error: 400, not a 502 from a thrown dereference.
source = replaceOnce(
  source,
  `        return json(400);
      }
      const part = Array.isArray(body?.parts)`,
  `        return json(400);
      }
      if (body === null || typeof body !== "object" || Array.isArray(body)) return json(400);
      const part = Array.isArray(body?.parts)`,
);
// 3. When OpenCode disposes this instance it may load plugins again in the
//    same process: release the claim so the next load serves.
source = replaceOnce(
  source,
  `        case "server.instance.disposed":
          break;`,
  `        case "server.instance.disposed":
          // Stop this instance's listener and remove its socket and record,
          // so a reload in the same process binds them afresh.
          stopped = true;
          clearTimeout(startup);
          process.removeListener("exit", close);
          close();
          if (globalThis[CLAIM] === claim) delete globalThis[CLAIM];
          break;`,
);
source = replaceOnce(
  source,
  `  setTimeout(async () => {
    const started = startedOn();`,
  `  const startup = setTimeout(async () => {
    const started = startedOn();`,
);
// 4. Once stopped, nothing (a late event, the startup timer) rewrites the
//    record of a disposed instance.
source = replaceOnce(
  source,
  `  let writing = Promise.resolve();
  function save() {
    writing = writing
      .then(() => {`,
  `  let writing = Promise.resolve();
  let stopped = false;
  function save() {
    writing = writing
      .then(() => {
        if (stopped) return;`,
);
source = replaceOnce(
  source,
  `  if (globalThis[CLAIM]) return {};
  globalThis[CLAIM] = VERSION;`,
  `  if (globalThis[CLAIM]) return {};
  const claim = { version: VERSION };
  globalThis[CLAIM] = claim;`,
);

for (const placeholder of ["__RUNTIME__", "__VERSION__"]) {
  if (source.includes(placeholder)) throw new Error(`${placeholder} left in output`);
}

if (check) {
  const current = fs.existsSync(output) ? fs.readFileSync(output, "utf8") : "";
  if (current !== source) {
    console.error("index.js is stale: run node scripts/build.mjs <relay-desktop checkout>");
    process.exit(1);
  }
  console.log("index.js matches the desktop template");
} else {
  fs.writeFileSync(output, source);
  console.log(`wrote index.js (protocol version ${version}, template ${commit})`);
}
