#!/usr/bin/env node
// Renders index.js from the Agent Relay desktop's OpenCode plugin template,
// so the npm package speaks exactly the protocol the desktop's probe expects.
//
//   node scripts/build.mjs <relay-desktop checkout> [--check]
//
// The template is probe/src/relay/opencode/agent-relay.js and the version is
// PLUGIN_VERSION in probe/src/relay/opencode.rs. --check fails when the
// committed index.js differs from what the template renders.

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const output = path.join(here, "..", "index.js");
const args = process.argv.slice(2);
const check = args.includes("--check");
const desktopArg = args.find((arg) => !arg.startsWith("--"));
if (!desktopArg) {
  console.error("usage: node scripts/build.mjs <relay-desktop checkout> [--check]");
  process.exit(2);
}
// Absolute, so the git pathspec below resolves from inside the checkout.
const desktop = path.resolve(desktopArg);

const templatePath = path.join(desktop, "probe/src/relay/opencode/agent-relay.js");
const rustPath = path.join(desktop, "probe/src/relay/opencode.rs");
const template = fs.readFileSync(templatePath, "utf8");
const version = /pub const PLUGIN_VERSION: u32 = (\d+);/.exec(fs.readFileSync(rustPath, "utf8"))?.[1];
if (!version) throw new Error("PLUGIN_VERSION not found in opencode.rs");
let commit = "unknown";
try {
  commit = execFileSync("git", ["-C", desktop, "log", "-1", "--format=%h", "--", "probe/src/relay/opencode/agent-relay.js"], {
    encoding: "utf8",
  }).trim() || "unknown";
} catch {}

function replaceOnce(source, from, to) {
  const index = source.indexOf(from);
  if (index < 0 || source.indexOf(from, index + from.length) >= 0) {
    throw new Error(`template changed: expected exactly one ${JSON.stringify(from.slice(0, 60))}`);
  }
  return source.slice(0, index) + to + source.slice(index + from.length);
}

let source = template;
source = replaceOnce(
  source,
  `// Installed and removed by Agent Relay's "OpenCode sessions" setting; edits
// to this file are overwritten. AGENT_RELAY_OPENCODE_PLUGIN=__VERSION__
`,
  `// npm package @agent-relay/opencode-plugin, loaded from opencode.json's
// plugin list. Generated by scripts/build.mjs from the Agent Relay desktop's
// plugin (protocol version ${version}, template ${commit}); do not edit.
//
// When the desktop's own copy is installed in OpenCode's plugins directory
// (it carries AGENT_RELAY_OPENCODE_PLUGIN=), or the person turned the
// desktop's OpenCode setting off (agent-relay.js.off), this package does
// nothing, so the plugin never runs twice in one process.
`,
);
source = replaceOnce(source, `import path from "node:path";\n`, `import os from "node:os";\nimport path from "node:path";\n`);
source = replaceOnce(
  source,
  "const RUNTIME = __RUNTIME__;",
  `const RUNTIME = path.join(os.homedir(), ".agentworkforce", "desktop", "opencode");`,
);
source = replaceOnce(source, "const VERSION = __VERSION__;", `const VERSION = ${version};`);
source = replaceOnce(
  source,
  `// The npm build replaces only this filesystem check. The process-wide claim
// also protects the desktop's managed copy when V2 loads several locations.
function deferToDesktop() {
  return false;
}`,
  `// OpenCode's global config directory, as OpenCode and the desktop resolve it.
function configDirectory() {
  const xdg = process.env.XDG_CONFIG_HOME?.trim();
  return path.join(xdg && xdg.startsWith("/") ? xdg : path.join(os.homedir(), ".config"), "opencode");
}

// The desktop's copy of this plugin serves the process, or the person turned
// the desktop's OpenCode setting off. Either way this package stays out.
function deferToDesktop() {
  const file = path.join(configDirectory(), "plugins", "agent-relay.js");
  if (fs.existsSync(\`\${file}.off\`)) return true;
  try {
    const head = fs.readFileSync(file, "utf8").split("\\n").slice(0, 5);
    return head.some((line) => line.includes("AGENT_RELAY_OPENCODE_PLUGIN="));
  } catch {
    return false;
  }
}`,
);

for (const placeholder of ["__RUNTIME__", "__VERSION__"]) {
  if (source.includes(placeholder)) throw new Error(`${placeholder} left in output`);
}

if (check) {
  const current = fs.existsSync(output) ? fs.readFileSync(output, "utf8") : "";
  if (current !== source) {
    console.error("index.js is stale: run node scripts/build.mjs <relay-desktop checkout>");
    process.exit(1);
  }
  console.log("index.js matches the desktop template");
} else {
  fs.writeFileSync(output, source);
  console.log(`wrote index.js (protocol version ${version}, template ${commit})`);
}
